### ISSUE TITLE
rest api: user passwort / key ring mindestlaenge

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#1]
IST:
- kann user mit IMHO zu kurzen passwort und key ring registireren
- kann user mit selben passwort und key ring registrieren

SOLL (IMHO):
- fehlermedlung: "passwort/key ring muss mindestens n zeichen lang sein"
- fehlermeldung: "passwort und key ring duerfen nicht ident sein"

**Comment by keros** [comment]
Ich muss noch nachschauen aber ich glaube wir hatten entschieden, dass das User PWD und das key ring PWD gleich sein dürfen.
Das ganze zwecks der Userfreundlichkeit.

**Comment by ghost** [comment]
Korrekt, Passwort und KeyRing dürfen de facto gleich bleiben; also für den ersten Prototyp reicht es, beim Parameter keyRing immer das User-Passwort zu übergeben.

Die Länge muss allerdings wirklich vorgegeben werden.

**Comment by ghost** [comment]
Die Geschäftslogik überprüft nun die minimale Länge für User PWD und KeyRing PWD.
Die Konfiguration erfolgt in bl.properties: 

```
minimalPasswordLength = 8
```

Das Mindestlänge ist derzeit auf 8 Zeichen gesetzt.
Der REST-Layer schickt bei zu kurzem Passwort errorCode 400 (BAD_REQUEST) mit folgenden JSON-Daten:

```
{u'errorType': u'org.backmeup.model.exceptions.PasswordTooShortException', u'errorMessage': u'The given password/keyring has to exceed at least 8 characters!'}
```

Revision 9e6f83aef9d9365e0602c1f3383dc443f51ecfa6
