### ISSUE TITLE
Does "Storage.move" create the new path?

### ISSUE THREAD

**Issue by keros** [backmeup/backmeup-prototype#10]
File Path: bmu_facebook_04.09.2012/dir1/dir2/file1

storage.move ("bmu_facebook_04.09.2012/dir1/dir2/file1", "bmu_facebook_04.09.2012_part1/dir1/dir2/file1");

Does the move command automatically create the new top folder and all sub folders?

**Comment by ghost** [comment]
Yes: The LocalFilesystemStorage creates all folders. We are using FileUtils.moveFile from org.apache.commons.io which creates all sub folders. (http://commons.apache.org/io/api-release/org/apache/commons/io/FileUtils.html)

However: The root folder of the backup (bmu_facebook_04.09.2012) cannot be referenced by the move command. You might only access files that are located within the root folder:

storage.move ("dir1/dir2/file1", "part1/dir1/dir2/file1");
