### ISSUE TITLE
insufficent information about action plugin options...

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#100]
getting the available actions for backup-jobs looks like this:

```
... GET ...
####### url: http://localhost:8080/actions/
###### data: None
########### response
#### status: 200
###### json: {
  "actions": [
    {
      "actionId": "org.backmeup.indexer", 
      "description": "The indexer plugin ", 
      "title": "Indexer "
    }, 
    {
      "actionId": "org.backmeup.filesplitting", 
      "description": "The file splitter plugin which splits files that exceed a certain file size ", 
      "title": "File Splitter "
    }, 
    {
      "actionId": "org.backmeup.encryption", 
      "description": "This plugin encrypts all files by using TrueCrypt", 
      "title": "Encryption Plugin"
    }
  ]
}
```

by convention these actions are visualized in the frontend as checkboxes. and an "array" of actions will be sent when creating the backub jobs. ie:

```
'actions': [u'org.backmeup.indexer']
```

but an action can also have "options":

```
... GET ...
####### url: http://localhost:8080/actions/org.backmeup.encryption/options/
###### data: None
########### response
#### status: 200
###### json: {
  "actionOptions": [
    "org.backmeup.encryption.password"
  ]
}
```

following issue comes up: how to determine if this action-option is a checkbox or a text input in the frontend?

solutions:
- hot fix: by convention it is always a text input. not the best but maybe fastest solution.
- the rest api sends more metadata like this:

```
"actionOptions": [
  {
    name: "org.backmeup.encryption.password",
    label: "Encyption Password",
    type: "string",
    required: true,
    ...
  },
]
```

**Comment by ghost** [comment]
For now, we only have the "org.backmeup.encryption.password" option for the encryption plugin and therefore it is sufficient to use text boxes for action options.

**Comment by fetzig** [comment]
> For now, we only have the "org.backmeup.encryption.password" option for the encryption plugin

not true. please check all the /actions/{action}/options/ call's. at least one returns dummy options. those need to go away.

> and therefore it is sufficient to use text boxes for action options.

ok thx
