### ISSUE TITLE
Properties created-at and modified-at for indexed elements

### ISSUE THREAD

**Issue by WolfgangEibner** [backmeup/backmeup-prototype#102]
All plugins should provide this (if possible) and use a common name. UI should show this properties in search results if they exist.

**Comment by WolfgangEibner** [comment]
Moodle, Facebook and Twitter should be okay
Dropbox, Skydrive and Mail should be checked

**Comment by ghost** [comment]
Dropbox API only provides the 'modified' flag
Mail plugin sets the attributes 'receivedAt' and 'sentAt' instead of a modified / created flag.

**Comment by WolfgangEibner** [comment]
UI work in backmeup/backmeup-frontend#33.
