### ISSUE TITLE
REST api: missing rest call [GET] /jobs/{username}/{jobID}

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#12]
can't get detailed data of a backup job.

i.e.: [GET] /jobs/{username}/{jobID} doesen't work.

would need stuff like, name, createtime,...

**Comment by fetzig** [comment]
adding those properties to the response of [GET] /jobs/{username}/ would fix it for me too.

**Comment by fetzig** [comment]
same with datasource and datasink profiles.

way to little info responds from [GET] /dataskink/{username}/profiles

so either put more info in the existing rest call (what plugin, createtime,...) or add a additional call like this

[GET] /datasink/{username}/profiles/{profileID}

**Comment by ghost** [comment]
Please post a detailed list of information you would like to get. I'll add them to both [GET] /jobs/{username}/ and [GET] /datasink/{username}/profiles.

**Comment by fetzig** [comment]
plugin_name, name, create- and modifytime should do it for the start.

**Comment by fetzig** [comment]
reminder...

[GET] /jobs/{username}/
- plugin_name, i.e. "org.backmeup.facebook" or "facebook"
- job title
- createtime
- modifytime
- current status (pending, queued, in progress, done,....???) 

[GET] /datasink/{username}/profiles
and 
[GET] /datasource/{username}/profiles
- plugin_name, i.e. "org.backmeup.facebook" or "facebook"
- createtime
- modifytime

**Comment by keros** [comment]
[Post] "/jobs/{username}" takes now an extra value (jobTitle) if an job gets created. Details in plone.
[Get] "/jobs/{username}" returns now more Information

**Comment by fetzig** [comment]
never (intentionally) requested it, but job title seems way more useful than "datasource/sink profile title". so +1 on that.

will check the changes and send feedback or close the issue.

thx.

**Comment by keros** [comment]
its not fixed yet
"[GET] /datasink/{username}/profiles" and "[GET] /datasource/{username}/profiles" enhancement are missing

**Comment by keros** [comment]
I have rebuild the core.
Job and source/sink return now more Informations.
To get a full List four rest calls are needed.
1: Get jobs -> returns all job Informations
2/3: Get Source/Sink -> returns alls Source/Sink Informations
4: Get Status (The job itself has no current Status.)

**Comment by WolfgangEibner** [comment]
Klemens: Does this fulfill your needs?

**Comment by fetzig** [comment]
this issue is deprecated anyways. so i'm closing this now.
