### ISSUE TITLE
no backups

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#16]
have created plenty of backup jobs by now (moodle -> dropbox). no actual backup was created on my dropbox.

**Comment by ghost** [comment]
I tested this with the latest version and the BackMeUp REST layer's create backup method ([POST] /jobs/{username})  didn't trigger. Please take a look at the frontend logs to determine what's going wrong.

**Comment by fetzig** [comment]
this issue has nothing to do with the web frontend...thus functionality shouldn't be tested via frontend.

...anyways seems like the issue has been solved. thx.
