### ISSUE TITLE
REST api: /jobs/{username}/status and /jobs/{username}/status/overview

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#17]
returns

``` javascript
{
  "errorType": "java.lang.NullPointerException"
}
```

**Comment by fetzig** [comment]
or returns an empty object:

``` javascript
{}
```

but i have at least 2 jobs.

**Comment by fetzig** [comment]
[GET] /jobs/{username}/{jobId}/status

returns an empty object as well. no matter if i add fromDate/toDate or not.

**Comment by ghost** [comment]
Currently no status information is being stored in the database by the job execution engine. We need an easy way to connect to the database and store new status entries (maybe by using the DAL layer).

**Comment by ghost** [comment]
/jobs/{username}/status/overview has been implemented as described in #41; 
/jobs/{username}/status will be implemented as described in #42
