### ISSUE TITLE
questions regarding: REST call [GET] /jobs/{username}/{fileId}/details - Protokoll-Details

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#19]
no idea how to retrieve a "fileId". can't even get detailed info and/or status info of a certain backup job. please clarify.

in other words:
how do i get a list of all files of a backup job? have i missed something? maybe a short introduction ("howto retrieve a backup jobs (meta)data the rest way?") would help.

**Comment by fetzig** [comment]
NOTE: using a just any "fileId" (an integer) returns "nothing" (not even an errror like: unkown fileId).

i.e.:
request:
[GET] /jobs/test_05@xxxx.xx/23/details

response (body):

``` javascript
 {}
```

**Comment by ghost** [comment]
This is an unimplemented feature. I've sent you the presentation which describes the basic idea behind the REST API (and the former Mockups). 

The workflow would be as follows:
- Get the actual protocol (/jobs/{username}/status); it contains a list of newly backed up files + fileId.
- When you click on a file, query its details (/jobs/{username}/{fileId})

A list of unimplemented features will be presented today @ the meeting.

**Comment by ghost** [comment]
Implemented as follows:

```
GET /jobs/TestUser/{fileId}/details

GET /jobs/TestUser/80:fcb9233e59681e4518cc26bc9fc7c2bb:1350293003815/details
```

Returns following data:

```
{
  u'details' : 
  {
    u'fileInfo': 
    {
      # the title of the file
      u'title': u'plain.txt', 
      # when has the file been backed up
      u'timeStamp': u'1350293003815', 
      # name of the source profile
      u'source': u'SrcProfile', 
      # name of the sink profile
      u'sink': u'SinkProfile', 
      # path in destination
      u'path': u'/folder1/folder2/plain.txt', 
      # MIME type of the file
      u'type': u'text/plain; charset=ISO-8859-1', 
      # file id again
      u'fileId': u'80:fcb9233e59681e4518cc26bc9fc7c2bb:1350293003815'
    }
  }
}
```

As described above, you may get fileIds by calling /jobs/{username}/status

**Comment by ghost** [comment]
deployed and tested via REST on dev01

**Comment by ghost** [comment]
Updated REST documentation and retested it on dev02 -> closing
