### ISSUE TITLE
rest api: email validierung

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#2]
- bei der registierung kann ein beliebiger string als email angegeben werde.
- wenn der parameter ein leestring ist bekommt man vom server gar keinen response -> timeout

**Comment by ghost** [comment]
Ab Revision 9e6f83aef9d9365e0602c1f3383dc443f51ecfa6 prüft die Geschäftslogik die E-Mail-Adresse während der Registrierung. Die erhaltene Adresse wird mit einem regulären Ausdruck überprüft. Der Ausdruck kann in bl.properties eingestellt werden:

```
# email regex provided by http://www.regular-expressions.info/email.html
emailRegex = ^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$
```

Sollte die E-Mail-Adresse ungültig sein, überträgt die REST-Schnittstelle folgende Nachricht (errorCode=400, BAD_REQUEST):

```
{u'errorType': u'org.backmeup.model.exceptions.NotAnEmailAddressException', u'errorMessage': u'The given email address "invalidemail.at" is invalid! The regular expression that has been used is: "^[A-Z0-9._%+-]+@[A-Z0-9.-]+.[A-Z]{2,4}$"'}
```

**Comment by ghost** [comment]
Der Timeout passiert, weil RESTEasy auf alle Parameter wartet, die in der Schnittstelle definiert wurden (in diesem Fall email-Parameter). Mögliche Lösung(en):
- OutputStream nach Versendung der Nachricht seitens Python schließen (wenn überhaupt möglich)
- E-Mail-Adresse immer mitübertragen
