### ISSUE TITLE
Alter PUT /users/{username} to allow changing username

### ISSUE THREAD

**Issue by WolfgangEibner** [backmeup/backmeup-prototype#26]
It should be also possible to change the username via this function. Also the description is not fully correct in plone (copy&paste error).

**Comment by ghost** [comment]
- The core is now capable of changing the username: 
  PUT /users/{oldUsername} Parameters {"username" : "MyNewUsername", "oldPassword" : "YourOIdPassword", "password" : "YourNewPassword", "email" : "YourNewEmail" }
- Removed unnecessary "keyRing" parameter.
- Updated plone and fixed copy & paste error.
- Updated and tested changes with python-tests.
