### ISSUE TITLE
rest api: email validierung 2

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#3]
nach der registrierung soll der benutzer seine email "bestaetigen".

d.h.
- backmeup-prototype soll email an den benutzer mit "key" bzw. link zum bestaetigen der email adresse schicken.
- via rest api soll backmeup-frontend den key (und username) an backmeup-prototype schicken und somit user's email adresse "freischalten".

link sollte dieses format haben:
https://backmeup.at/verify_email/<key>

**Comment by ghost** [comment]
BackMeUp schickt nun eine Nachricht an neu registrierte Benutzer, indem folgender (frei konfigurierbarer Text), gesendet wird:

```
Subject: Verify your backmeup account
To verify the email address of your backmeup account, open the following link in your browser:
https://backmeup.at/verify_email/adfasjfoasjioaSDFjadfajiowWER
If you didn't request a backmeup account, ignore this mail.
```

Die URL zu der zurückgeleitet werden soll, kann in bl.properties eingestellt werden:

```
emailVerificationUrl = https://backmeup.at/verify_email/%s
```

Anstelle `%s` setzt die Plattform einen eindeutigen generierten (Base64(SHA-256)) Verifizierungsschlüssel ein.
Nach Umleitung zur emailVerificationUrl muss folgende neue REST-Methode im Kern aufgerufen werden:

```
/users/{verificationKey}/verifyEmail
```

Bei erfolgreicher Aktivierung des Benutzers liefert die Methode den statusCode=204 (NO_CONTENT). Kann ein User nicht aktiviert werden (ungültiger verificationKey), wird Fehlernachricht (errorCode=400) gesendet:

```
{
  u'errorType': u'org.backmeup.model.exceptions.EmailVerificationException', u'errorMessage': u'Failed to verify key abc'
}
```

Alle REST-Methoden (bis auf deleteUser) überprüfen, ob der User aktiviert ist, bevor sie die eigentliche Arbeit durchführen. Sollte ein Benutzer nicht aktiviert sein, sendet die REST-Schnittstelle folgenden Fehler (status=400, BAD_REQUEST):

```
{
  u'errorType': u'org.backmeup.model.exceptions.UserNotActivatedException',  
  u'errorMessage': u'User TestUser has not been activated!'
}
```

Die REST-Schnittstelle besitzt außerdem eine zusätzliche Methode `/users/{username}/newVerificationEmail`,
um die Verifizierungsnachricht erneut an die jeweilig hinterlegte Adresse zu senden.

**Comment by fetzig** [comment]
erst mal: super, danke.

kleiner typo is noch im code, wenn das fuer euch ok ist kann ich sowas in zukunft selbst korrigieren (weiß aber nicht mal ob ich "push rechte" in dem repository hab...)

see: https://github.com/backmeup/backmeup-prototype/blob/master/org.backmeup.rest/src/main/java/org/backmeup/rest/Users.java#L74

IS:
/users/{verificationKey}/verfiyEmail

SHOULD:
/users/{verificationKey}/verifyEmail

**Comment by ghost** [comment]
Bitte typos in Zukunft gleich selbst korrigieren!
(mit Revision 480df036d60f6604290756d5d9d4b3144c49207d erledigt)
