### ISSUE TITLE
facebook authentication fail

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#33]
when trying to create a "facebook datasource profile" via web ui the redirect url from facebook back to backmeup looks like this:

```
.../oauth_callback/#access_token=asdf&expires_in=4213
```

but should be:

```
.../oauth_callback/?access_token=asdf&expires_in=4213
```

short: need oath/access token and other access params as URL GET param(s)

**Comment by mmurauer** [comment]
the redirect url is not created from our plugin but from the facebook-api.
for more info follow this link: https://developers.facebook.com/docs/reference/dialogs/oauth/

**Comment by fetzig** [comment]
according to my log the backmeup rest api responds a redirect url with looks like this:

```
https://www.facebook.com/dialog/oauth?....&response_type=token&...
```

but should respond a redirect url like this:

```
https://www.facebook.com/dialog/oauth?....&response_type=code&...
```

(sorry to dissapoint but this seems to be no bug in the facebook-api)

**Comment by mmurauer** [comment]
if we change the redirect url to "response_type=code" we need an additional request to the facebook-api to exchange the received code for a access token:
https://graph.facebook.com/oauth/access_token?
client_id=YOUR_APP_ID
&redirect_uri=YOUR_REDIRECT_URI
&client_secret=YOUR_APP_SECRET
&code=CODE_GENERATED_BY_FACEBOOK

I don't know if the plugin-api is designed for this?

**Comment by fetzig** [comment]
don't know anything about the plugin-api or the facebook-api (just checked that "response_type=code" would be a possible solution).

as the issue describes i need http url/get params (like when using the dropbox plugin).

**Comment by ghost** [comment]
This seems to be related to the facebook-plugin's authentication implementation: Try to encode the redirect URL with URLEncoder.encode(redirectUrl)
But I am not sure if that's the actual problem; further investigations will take place next week

**Comment by ghost** [comment]
fetzig stated that we might change to response_type=code to get a "?" instead of a "#" within the callback of facebook. Michaela, is this a suitable solution for the authentication mechanism?

**Comment by fetzig** [comment]
auth request fb plugin looks like this:

```
POST /datasources/username/org.backmeup.facebook/auth
```

response is:

``` javascript
{
    'redirectURL': 'https://www.facebook.com/dialog/oauth?...',
    'profileId': '497',
    'type': 'OAuth',
    'sourceProfile': true
}
```

type: OAuth...like the dropbox plugin. but thats not the case (missing get params in the redirect). so we have 2 possibilities (at least as far as i understand):
- changing the type to something else and documenting how the rest api client should deal with this new type. which needs a new implementation on the frontend side.
- make the process identical to the process of dropbox

**Comment by fjungwirth** [comment]
authentication works now and the backup starts.
parts of the job work well, but an error occured while downloading Users.
We will fix that asap
