### ISSUE TITLE
twitter authentication fail

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#34]
get following error via rest api when trying to create a "twitter datasource profile":

request:

```
post url: http://localhost:8080/datasources/username/org.backmeup.twitterx/auth
post data: {'profileName': u'org.backmeup.twitterx - profile', 'keyRing': u'123456789'}
```

response:

```
 <Response [400]>
{u'errorType': u'org.backmeup.model.exceptions.PluginException', u'errorMessage': u"Plugin '(name=org.backmeup.twitterx)': Plug-In service of class 'org.backmeup.plugin.spi.Authorizable' not available!"}
```

**Comment by mmurauer** [comment]
plugin-name should be org.backmeup.twitter instead of org.backmeup.twitterx

**Comment by fetzig** [comment]
according to the rest api's response there is the twitterx plugin but no twitter plugin:

get request: /datasources

``` javascript
{
  "sources": [
    ...
    {
      "title": "BackMeUp Twitter Plug-In",
      "imageURL": "https://twitter.com/images/resources/twitter-bird-light-bgs.png",
      "datasourceId": "org.backmeup.twitterx"
    }
    ...
  ]
}
```

this might be a "build error" or "implementation bug".

**Comment by mmurauer** [comment]
found the mistake and uploaded the correct version

**Comment by ghost** [comment]
Is this issue still relevant? Otherwise we can close it.

**Comment by fetzig** [comment]
wont close it until the bug is fixed on the server...thats not the case yet.

**Comment by fetzig** [comment]
still not deployed.

**Comment by keros** [comment]
new twitter plugin is now deployed

**Comment by fjungwirth** [comment]
seems to work now, just did a backup from twitter to dropbox
