### ISSUE TITLE
dropbox and moodle plugin/profile options fail

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#35]
tried to (finally) implement profile options to the web ui. when requesting the options of a profile/datasource the rest api responds with an error.

profile is dropbox. same/similar error with moodle. seems to work with facebook. 

post request:

```
url: /datasources/username/profiles/391/options
post data: {'keyRing': u'asdf'}
```

response:

```
<Response [400]>
{u'errorType': u'org.backmeup.model.exceptions.PluginException', u'errorMessage': u'An exception occured during execution of the method getAvailableOptions'}
```

**Comment by keros** [comment]
I have now tested it.
Moodle and Facebook plugins work fine.

Dropbox works for my account but not for fetzigs account.
There is some Problem with the implementation of the function in the dropbox Blugin

**Comment by fetzig** [comment]
please assign the ticket to yourself if you work on it. thx.

**Comment by fetzig** [comment]
fyi: dropbox doesn't work with a newly created user as well.

**Comment by keros** [comment]
thx for the info. I think fschoeppl will fix his Plugin, thats why I have not reasigned it to myself

**Comment by ghost** [comment]
Dropbox-Error: This is related to the fact, that the tokens for user fetzig_10 are invalid.

Therefore the core / plugin needs to throw a special Exception that indicates such authorization errors.

Workaround should be: Recreate the dropbox-profile
