### ISSUE TITLE
Dropbox access tokens limitation

### ISSUE THREAD

**Issue by bdf-net** [backmeup/backmeup-prototype#36]
When trying to create a dropbox-backup I get the message "Only a limited set of users can receive access tokens while this app is in development mode".

Is it possible to grant access for another user?
Otherwise we would have to delete the account of fetzig and create a shared test-account.

**Comment by WolfgangEibner** [comment]
I think this limitation only exists as long as our application is not registered at dropbox. And I think it is something like "Only 5 accounts in a hour" or so. There was something in the last meeting about this. Fabian?

**Comment by keros** [comment]
If backmeup is not registered @ dropbox only 5 accounts can be connected to backmeup.
But you can use my account "ft@x-net.at", "Test1234!".
I have only used it for testing.

**Comment by bdf-net** [comment]
thanks a lot, this will work for now!
