### ISSUE TITLE
moodle -> dropbox backup isn't saved in subfolder

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#38]
- test from web ui by creating a backup: moodle (all options checked) -> dropbox .
- backup (seems) to work but files aren't packed in one "job" folder.

dropbox folder after backup:

```
mymachine:~/Dropbox sepp$ ls -al
...
drwxr-xr-x  12 sepp  staff     408  5 Okt 15:20 Backmeup Kurs #1
drwxr-xr-x  72 sepp  staff    2448  5 Okt 15:21 Game Based Learning
-rw-r--r--   1 sepp  staff    4508  5 Okt 15:19 adlcp_rootv1p2.xsd
-rw-r--r--   1 sepp  staff    1236  5 Okt 15:19 ims_xml.xsd
-rw-r--r--   1 sepp  staff   14905  5 Okt 15:19 imscp_rootv1p1p2.xsd
...
mymachine:~/Dropbox sepp$
```

**Comment by keros** [comment]
This is an side effect of the new sorage system in the core.
The Plugin have now to create its own subfolder.
The subfolder name is provided in the properties that where send to the plugin ("org.backmeup.tmpdir").
