### ISSUE TITLE
needed properties/changes in rest api response

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#42]
NOTE: this is a draft request from the "frontend dev" which has very little to no knowledge of the inner workings of backmeup. so feel free to send feedback if there is a different approach from the "backmeup core perspective" that could save us time or nerves (now or in the future).
### /jobs/{username}/{jobId}/status
- filter of log: filter log not by time but return log of last created backup only.
- type/category/progress/status: need 2 properties
  - one that indicates the current status of the job when this log entry was made: done, busy, finished,...
  - one that indicates the type of log message:  warn, error, store, user action,...
- message: should be a message id (gettext). thus no dynamic values in the message. dynamic values in messages could work like this:

``` javascript
...
message: 'Today is %(month)s %(day)s.',
message_dict: {'month': 10, 'day': 10}
...
```
### /data[sinks|sources]/{username}/profiles
- datasink/datasource profiles account/username: the email/username of the authenticated account.
- datasink/datasoure profile options: get the currently selected options of the profile
- no need to give a datasink/datasource profile a title as long as we know the plugin name and the user. thus this property should be dropped.
### /jobs/{username}/
- datasink/datasource profiles account/username: the email/username of the authenticated account.
- time of next backup
- time of last backup (this might be already "startDate")
- current status of job: done, in progress, error, warning
- optional status message: i.e. when status is error or warning

**Comment by fetzig** [comment]
still waiting for (complete) feedback to this issue (as requested via email). thx.

**Comment by rsimon** [comment]
The above three additions are now live on dev01 and dev02.

**Comment by ghost** [comment]
Updated /jobs/{username}[/{jobId}]/status:
Call doesn't need datefrom / dateto anymore:

GET /{username}/status
=> Returns the latest status of the latest executed job

GET /{username}/{jobId}/status
=> Returns the latest status of the given job

Data returned + Description:

```
{
  u'backupStatus': [{ 
    # the category of the Status: 
    #  STORE ... these entries will be made during the backup
    #  ACTION ... an action took place, e.g. message : "Dropbox hinzugefügt"; Note: Currently only STORE will be returned
    u'category': u'STORE', 
    # the files belonging to the job
    u'files': [
      { 
        # when
        u'timeStamp': 1350293651919, 
        # file identifier for /job/{username}/{fileId}details call.
        u'fileId': u'63:fcb9233e59681e4518cc26bc9fc7c2bb:1350293651919', 
        # title of the file
        u'title': u'plain.txt'
        # Note: We don't have any thumbnails
      }, 
      {
       u'timeStamp': 1350293652105, 
       u'fileId': u'63:85cf76d73767062185883b758dc54c5b:1350293652105', 
       u'title': u'html.txt'
      }
    ], 
    # timestamp of the status entry
    u'timeStamp': u'1350293652190', 
    # the job which belongs to this status
    u'jobId': 21, 
    # The message of the status:
    # We don't know which / how many files have been backed up => Messages might only contain information about sinks / sources / backupjobname:
    #   Facebook -> Dropbox  
    #   Mein Facebook zu Dropbox Job
    u'message': u'BackupJob Completed', 
    # the current state of the backup job:
    # BUSY ... job is currently being executed
    # FINISHED ... job ran successfully
    # ERROR ... an error occurred during execution of the job; Message contains the error message
    # 
    u'type': u'FINISHED'
  }
]}
```

**Comment by ghost** [comment]
Implementation of #19 and #42 deployed and tested via REST on dev01

**Comment by ghost** [comment]
Added a call to get the currently stored datasource options:

```
GET /datasource/{username}/profiles/{profileId}/{jobId}/storedOptions
```

returns:

```
{
  u'sourceOptions': [
    u'option1', 
    u'option2', 
    u'option3', 
  ]
}
```

all commited features are deployed on dev01 and dev02

**Comment by ghost** [comment]
/jobs/{username}/{jobId}/status and /jobs/{username}/status now return the full logs of the latest job execution.
