### ISSUE TITLE
search not working: [POST] /backups/{username}/search

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#43]
attempt to get a search id failed:

``` javascript
[POST] /backups/{username}/search

HTTP 400
{
  "errorMessage":"An error occured",
  "errorType":"org.backmeup.model.exceptions.BackMeUpException"
}
```

please clarify if search feature:
- isn't finished yet
- this is a bug
- docu is deprecated and i'm doing something wrong

**Comment by ghost** [comment]
Core updated and successfully tested via REST

**Comment by rsimon** [comment]
Just verified that this works on dev01, with username=TestUser

```
[POST] /backups/{username}/search
```

requires a _keyRing_ and a _query_ parameter. Another cause may be that the username doesn't exist in the DB. (I tried this as well, and it returns exactly the response you describe.)

**Comment by fetzig** [comment]
cause is: docu is deprecated and i'm doing something wrong

so please update the docs

**Comment by WolfgangEibner** [comment]
docu on plone updated (as far as I see)
