### ISSUE TITLE
how to set actions (+ action options) when creating a job?

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#45]
[POST] /jobs/{username}

who to set multiple actions, and how to set action options when creating a backupjob?

example in docs sets one action only (no options):

``` javascript
requiredActions=org.backmeup.rsa
```

**Comment by ghost** [comment]
Not yet designed/implemented; I'll drop you the REST calls + data returned after I designed and implemented it

**Comment by ghost** [comment]
To set more requiredActions, pass in form parameters encoded with following format:

requiredActions=org.backmeup.rsa&requiredActions=org.backmeup.indexer&requiredActions=org.backmeup.anotherAction

ActionOptions cannot be changed yet.

**Comment by ghost** [comment]
Available action options can be retrieved as follows:

```
GET /actions/{actionId}/options
e.g.: GET /actions/org.backmeup.filesplitting/options
```

returns:

```
{
  u'actionOptions': [
    # each settable option of the action plugin 
    u'Test Option 1', 
    u'Test Option 2'
  ]
}
```

Change action options of certain action and job:

```
PUT /actions/{actionId}/options/{jobId}
Form-Parameters: {"Test Option 1" : "true", "Test Option 2" : "true"}

e.g.: PUT /actions/org.backmeup.indexer/options/3
Form-Parameters: { "useAllMetdata" : "true" }
```

Get stored action options of a certain action and job:

```
GET /actions/{actionId}/storedOptions/{jobId}
e.g.: GET /actions/org.backmeup.filesplitting/storedOptions/30
```

returns:

```
{
  u'actionOptions': [
    # returns each set option
    u'splitFolder'
  ]
}
```

**Comment by ghost** [comment]
deployed and tested (via REST) on dev02 and dev01

**Comment by fetzig** [comment]
thx. please update the rest api docu.

**Comment by ghost** [comment]
ok, I just added the things described here to the rest docu

**Comment by ghost** [comment]
tested and documented -> closing
