### ISSUE TITLE
improve /datasources/{username}/{datasourceId}/auth 2

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#47]
"meta info" is way to little.

IS:

``` javascript
{
  'profileId': '14',
  'requiredInputs': [
    'Username',
    'Password',
    'Type',
    'Host',
    'Port',
    'SSL'
  ],
  'sourceProfile': true,
  'type': 'Input',
  'typeMapping': {
    'Username': 'String',
    'SSL': 'Bool',
    'Host': 'String',
    'Password': 'Password',
    'Type': 'String', 
    'Port': 'Number'
  }
}
```

troubles on frontend side:
- order (see issue #46)
- additional info/helptext (how to add one, when to add one)
- requiredInputs shouldn't be an extra array, rather pack everything in an object.

SHOULD (i.e.):

``` javascript
{
  'profileId': '14',
  'sourceProfile': true,
  'type': 'Input',
  'fields': {
    'username': {
      'type': 'string',
      'label': 'Username',
      'order': 1,
      'required': true,
    },
    'use_ssl': {
      'type': 'bool',
      'label': 'SSL',
      'order': 2,
      'helptext': 'use ssl',
      'required': false,
    },
    ...
  }
}
```

**Comment by keros** [comment]
I just creating an new Object for this.
String label;
String description;
boolean required;
int order;
Type type;

How should we translate the "description" (helptext) filed?
Should we maybe force the plugin writer to deliver an translation?

**Comment by keros** [comment]
Should also solve #46
Tested on dev02.
Note that "typeMapping" is now useless and returns a empty list.
I remove it in the next commits.

Mail Plugin for example now returns:

``` javascript
{
"type":"Input",
"profileId":"25",
"requiredInputs":
[
  {
    "type":"String",
    "description":"The username of your E-Mail account",
    "required":true,
    "order":0,
    "label":"Username"
  },
  {
    "type":"Password",
    "description":"The password of your E-Mail account",
    "required":true,
    "order":1,
    "label":"Password"
  },
  {
    "type":"String",
    "description":"IMAP or POP3",
    "required":true,
    "order":2,
    "label":"Type"
  },
  {
    "type":"String",
    "description":"The hostname of your E-Mail server",
    "required":true,
    "order":3,
    "label":"Host"
  },
  {
    "type":"Number",
    "description":"The port on which the plugin should connect to the E-Mail server",
    "required":true,
    "order":4,
    "label":"Port"
  },
  {
    "type":"Bool",
    "description":"Use SSL (encrypted connection)",
    "required":true,
    "order":5,
    "label":"SSL"
  }
],
"typeMapping":{},
"sourceProfile":true}
```

**Comment by keros** [comment]
Recompiled code on dev01. Is now live. Docu updated

**Comment by fetzig** [comment]
- changes are not as requested and misleading -> wrong
- requiredInputs??? there is a required param in it.
- the actual name of the parameter is missing (which would be there if done as anticipated)
- far to little documentation
  - typeMapping???
  - type: bool -> how should that look like when the auth/post request is done
  - type -> what possible types do exist and what are the implications

please improve/fix docu/code and let me know when it's done. thx.

**Comment by keros** [comment]
- requiredInputs??? there is a required param in it.
  I rename the List in the next commits to "fields".
- the actual name of the parameter is missing (which would be there if done as anticipat
  There is no difference between the "name" and the "label" of the input field. So I have not added an extra variable for this.
- far to little documentation
  - typeMapping???

As already said above this is currently a empty list and will be removed in the next commits. You can simply ignore the field.
- type: bool -> how should that look like when the auth/post request is done

How have you handled the "bool" before the patch? Before the "type" was given over the "typeMapping" field. There was "bool" already in it.
- type -> what possible types do exist and what are the implications

The same as before. There where no changes.

``` javascript
public enum Type
{
String,
Number,
Password,
Bool
}
```

**Comment by keros** [comment]
Updated Core on dev01.
Updated documentation on Plone.

**Comment by fetzig** [comment]
> How have you handled the "bool" before the patch? Before the "type" was given 
> over the "typeMapping" field. 
> There was "bool" already in it.

true, they have been ther for some time now. but still no info, or even docs describing how to handle them.

**Comment by fetzig** [comment]
> The same as before. There where no changes.

true, but i never got those infos. just because its in the backmeup-prototype code doesn't mean it's documented...please make sure this is in the documentation. thx.

and don't miss the fact that the rest api sends how to label the input field for the user but have no idea what the name (or key) of the value is when making the .../auth/post request. i mention it again because you have commented on everything but this.

once again to clarify:

``` javascript

// my proposal again:

'fields': { // don't care how to call it

    'username': { // key (this will be the name of the request param)

      'type': 'string', // indicates what kind of form field should be rendered (useful would be: text, checkbox, password)
      'label': 'Username', // label of form field
      'order': 1, // the order in which these form fields are rendered in the ui
      'required': true, // makes it possible to "prevalidate" form field
      //'description': 'username of your moodle account', // optional message id - should be translated in frontend
    },

// but i'm fine with this approach too:

{
    "name": "ssl" // key (this will be the name of the request param)
    "type":"Bool",
    "description":"Use SSL (encrypted connection)",
    "required":true,
    "order":5,
    "label":"SSL"
  }

```

thx.

**Comment by WolfgangEibner** [comment]
Return-type for Bool is "true" or "false"

**Comment by keros** [comment]
Updated Docu on Plone
