### ISSUE TITLE
ZIP Download

### ISSUE THREAD

**Issue by WolfgangEibner** [backmeup/backmeup-prototype#48]
Implement ZIP Download

Should be clarified:
- path where to store zip files
- access from frontend to zip files
- delete old zip files after an specific amount of time (cron job)

**Comment by ghost** [comment]
Note: The zip plugin doesn't need any input parameters. The list of required inputs will therefore be empty. 
In general: The frontend should skip to the next web page, if a plugin doesn't need any inputs (a call to postAuth can be omitted in these cases)

**Comment by ghost** [comment]
ZIP-Plugin is now deployed on dev02, copying the zip files to /tmp/backups/{userId}/{backupfilename}-{timestamp}.zip

@WolfgangEibner / @fetzig: Please specify the destination folder for the frontend on dev01 - I'll use the same as on dev02 for now.

@keros: I would also like to test the sftp feature. Please provide a ssh certificate + correct paths to copy to.
To do this, we have to configure the zip plugin's zip.properties file (src/main/resources/zip.properties) and rebuild it:

```
# {0} ... the user id
temporaryPath = /tmp/backups/{0}/
# note: If isRemote is true, the zip file will be copied to a sftp destination. 
isRemote = true
# {0} ... the user id, {1} ... the filename of the zip
remote.target = /tmp/backups/{0}/{1}
# {0} ... the user id
remote.directory = /tmp/backups/{0}/
remote.host = openrc2
remote.port = 22
remote.user = root
# maybe we want to use a different key here
ssh.key = /root/.ssh/id_rsa
```

These settings have been copied from the discmailing plugin.

**Comment by ghost** [comment]
Deployed and tested local zip file creation on dev01.

**Comment by keros** [comment]
You can use the "/root/.ssh/id_rsa" key file on the server.
The server can now ssh to itself with this keyfile.

Place the files on "/data/backmeup-frontend-backupfiles" or something like this.
Don't forget to change the "remote.host" to "localhost".

**Comment by ghost** [comment]
Ok, I just tested this on dev01.
Files will be placed via sftp on localhost /data/backmeup-frontend-backupfiles/{userId} after a zip backup job finished.

**Comment by ghost** [comment]
ZIP-Plugin working as follows:
- All files given by the Storage instance will be zipped to a temporary location
- If "isRemote" has been set to true, the temporary zip file will be copied via sftp to a remote directory.

dev01 settings:
ZIP-Backups will be copied to /data/backmeup-frontend-backupfiles/{userId} as proposed by keros.

Remaining steps:
- Display backup files within frontend.
- Implement a cron job which deletes old backups.

**Comment by keros** [comment]
Added cronjob to "bmu-dev01"

``` bash
00 05   * * *   root     find /data/backmeup-frontend-backupfiles -type f -mtime +1 -exec rm {} \;
```

Files older than one day get now deleted

**Comment by WolfgangEibner** [comment]
Closing because only thing left is listing available downloads in UI. Created an extra issue for this (see above).
