### ISSUE TITLE
FileSplitter: Split files according to maxFileSize from data sink

### ISSUE THREAD

**Issue by WolfgangEibner** [backmeup/backmeup-prototype#50]
maxFileSize should be included in properties given to the FileSplitter. Filesplitter should use this property for splitting the containers.

**Comment by keros** [comment]
Filesplitter works fine now. If no property "org.backmeup.filesplitting.maxcontainersize" is not set or if the value is "-1" then the maximum limit is set (1099511627776 Bytes = 1TiB).
Else the plugin uses the given container size from the plugin.

Currently there is no Sink Plugin that sets this setting.
