### ISSUE TITLE
Index: Deactivate and maybe delete index in UI/REST

### ISSUE THREAD

**Issue by WolfgangEibner** [backmeup/backmeup-prototype#55]
User should be able to deactivate indexing in UI. If indexing is deactivated no job for this user should do indexing action (also no existing periodical job). 
After indexing is deactivated in UI, it should ask, if the user want's to delete his existing index. If so, the necessary actions should be triggered by a REST call.

So we need a REST call to activate/deactivate indexing for a user. This is a global option. There will not be an job-local option for indexing. And we need a REST call for deleting a user's index.

**Comment by rsimon** [comment]
Fix commited in commit c543043a546fbdfb754e42ea3e060d6e0da270d0

**Comment by WolfgangEibner** [comment]
As far as I can see the global user property is named "enable.indexing".

@fetzig: Please implement the necessary changes in UI for global activation/deactivation of index like described above.

**Comment by rsimon** [comment]
PS: copying my E-Mail with instructions from Nov 8 for reference!

```
Hallo,

soweit ich informiert bin, habt ihr im letzten Skype-Meeting besprochen dass das Indexing nicht
mehr pro Job (de)aktiviert werden soll, sondern dass es ein globales Setting pro User gibt. (Indexing 
generell aktiv, oder generall deaktiviert.)

Das ist jetzt implementiert. Und zwar lässt es sich über die existierenden User Properties steuern. 
Siehe REST-IF Doku

http://backmeup.project.x-net.at/projekt/konzeption/technische-umsetzung/rest-schnittstelle/rest-schnittstelle

…in der Section „/users/{username}/properties/{property}/{value}”. Kurz gesagt muss einfach nur
eine property

„enable.indexing“

auf den Wert „true“ oder „false“ gesetzt werden. Der aktuelle Wert der Property kann (wie in der Doku 
beschrieben) über

/users/{username}/properties/enable.indexing

Abgefragt werden.

Sollte vom Frontend keine Property gesetzt werden, verwende ich innerhalb der Job-Abarbeitung
derzeit „true“ als default. (Ist zum Testen einfacher, da wir ansonsten alle Tests umschreiben 
müssten, so dass sie vor Ausführung die Property setzen…)

Ich weiss leider nicht, wo ich diese Info am besten dokumentieren soll. Gibt es bereits andere 
User Properties, die gesammelt dokumentiert sind? Falls nicht sollten wir das IMO gleich in die 
REST-Schnittstellen Doku packen!

 LG,
 Rainer
```

**Comment by WolfgangEibner** [comment]
Closing this in backmeup-prototype and created issue in backmeup-frontend instead.

**Comment by fetzig** [comment]
deleteIndex and setting global/user property doesn't need a keyRing...thus anybody can trigger those actions...

should require keyRing.

**Comment by WolfgangEibner** [comment]
@fschoeppl: Please add keyRing parameter to verify user.

**Comment by WolfgangEibner** [comment]
KeyRing is only needed on actions which really need it (e.g. creating a job, for communication with keyserver).
