### ISSUE TITLE
Scheduler: activate FileSplitter if necessary

### ISSUE THREAD

**Issue by WolfgangEibner** [backmeup/backmeup-prototype#58]
Scheduler should activate FileSplitter if 
- encryption is enabled and
- data sink has a limited file size

So, FileSplitter is not activated by user decision. Instead its usage should be determined automatically.

**Comment by rsimon** [comment]
Q: how do I find out whether the sink has a limited filesize? And which properties do I need to set to tell the FileSplitAction the chunck size?

**Comment by keros** [comment]
Little change.
The filesplitter must always run if the encryption plugin is enabled. Else the paths for the indexer will not be correct.

The property should be "org.backmeup.filesplitting.maxcontainersize".

The sinks should set an max filesize property "org.backmeup.{plugin}.maxfilesize".
If none is set just set "org.backmeup.filesplitting.maxcontainersize" to "-1". Then I simply create an container that includes all files in the current backup.

The size should be given to me in bytes.

**Comment by rsimon** [comment]
Ok, that simplifies things :-)... BUT: 

<The sinks should set an max filesize property "org.backmeup.{plugin}.maxfilesize".>

Is {plugin} the same String as delivered in "sinkprofile.description"? If so, I can filter out this property. But just as a remark: that means _every_ plugin uses a different property to set the limit. IMO we should just use something like  

"org.backmeup.sink.maxfilesize"

and this could be used directly in the Filesplit Plugin, if available.

**Comment by keros** [comment]
That was only my first idea.

"org.backmeup.sink.maxfilesize" would be the better way.

**Comment by rsimon** [comment]
+1

BTW: just committed a change to the BackupJobRunner. Filesplit will now be triggered when Encryption is selected (and Thumbnail rendering when indexing is selected). All source/sink properties should now be correctly handed to the action plugins!
