### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by WolfgangEibner** [backmeup/backmeup-prototype#59]
Do some performance tests, especially for the REST interface and for parallel job running.

**Comment by ghost** [comment]
The ParallelJobs.py script creates 100 threads, each starting 2 DummyToDummy backup jobs (=200 Jobs).
To test MoodleToZip-File use the ParallelJobsMoodleZip.py script.

To get help about the usage of the script, run following code: 

```
cd python-tests
python ParallelJobs[MoodleZip].py --help
```

**Comment by ghost** [comment]
Added tests script for following scenarios:
- E-Mail to Dropbox (ParallelJobsEmailDropbox.py)
- Facebook to Discmailing (ParallelJobsFacebookToDiscmailing.py)
- Skydrive to Zip (ParallelJobsSkydriveToZip.py)
- Twitter to Skydrive (ParallelJobsTwitterToSkydrive.py)

All scripts have been tested locally, further tests on dev02 will take place

**Comment by ghost** [comment]
Tests have been run and presented at the meeting
