### ISSUE TITLE
user registration to slow

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#6]
IS:
rest api processes the registration process synchron. which means the web frontend gets no response until the user is created _and_ his verification email was sent. the verification key is also added to the response.

SHOULD:
rest api should respond asap. there is no need for the frontend to get the verification key. sending the verification email should be done asynchronous (after the rest api send the response).

**Comment by ghost** [comment]
The verification key will be passed to the caller because python integration tests would like to automatically verify users during tests.

The mailer class now sends emails asynchronously improving performance drastically (Revision cae13cb513dc0933cc19c7d0df5b8ae4154c1660)
