### ISSUE TITLE
JobStatus

### ISSUE THREAD

**Issue by WolfgangEibner** [backmeup/backmeup-prototype#60]
Implement JobStatus according to last meeting: 
- Only return and save log of last backup for each job
- Include job status for each job in job listing

**Comment by WolfgangEibner** [comment]
Fix committed in e2c94f43ab775b75d2f791486cc1f6e87c9fbc42?

**Comment by ghost** [comment]
Yes, the fix has been committed in e2c94f43ab775b75d2f791486cc1f6e87c9fbc42
