### ISSUE TITLE
E-Mail notification after job failure

### ISSUE THREAD

**Issue by WolfgangEibner** [backmeup/backmeup-prototype#61]
If a backup job fails an email should be sent to inform the user.

**Comment by WolfgangEibner** [comment]
Failing BackupJob sends email as expected.

**Comment by bdf-net** [comment]
Email-notification works, but instead of _one_ email, countless emails are sent to the user.
Please sent one email for a backup-job with failures - instead of one email for every failure inside a backup-job (which I guess is what's happening at the moment).

**Comment by WolfgangEibner** [comment]
Problem seems to be rescheduling of jobs and not the e-mail itself. Should get fixed when rescheduling is fixed.
