### ISSUE TITLE
Save user identification from datasources/-sinks

### ISSUE THREAD

**Issue by WolfgangEibner** [backmeup/backmeup-prototype#65]
Save user identification (e.g. facebook username, dropbox login name) at authentication of datasource/-sink and return it to UI when retrieving job details. So UI can display which Facebook profile is used at a certain job.

**Comment by ghost** [comment]
The postAuthorize-method of the Authorizable interface now returns the User ID of the authorized account:

`public String postAuthorize(Properties inputProperties);`

I've updated all plugins to return at least null. The dropbox, skydrive and mail plugin already return the username.
Please upgrade the other plugins (Discmailing, Facebook, Moodle and Twitter) and report the changes here.

REST API documentation has been updated on Plone. 
Following REST calls return the identification attribute:
- GET /datasources/{username}/profiles
- GET /datasinks/{username}/profiles
- GET /jobs/{username}

**Comment by WolfgangEibner** [comment]
We will update Discmailing plugin asap...
