### ISSUE TITLE
MoodlePlugin: authentication error

### ISSUE THREAD

**Issue by WolfgangEibner** [backmeup/backmeup-prototype#66]
An authentication error in moodle plugin doesn't result in an appropriate message. Should be examined if it is a plugin, backend or UI error.

**Comment by fjungwirth** [comment]
The plugin provides a validate() method, which gives detailed information about an authentification error.
But there is also a isValid() method, which returns wether true or false. I'm not sure which method is used by the rest api

**Comment by ghost** [comment]
Use Case of the isValid()-method:
1. Core's preAuthentication method returns the required input fields (e.g. username + password)
2. User enters username + password
3. Core gets called with username + password as argument, which will be passed to the isValid-method of your validator.
4.1. If the username + password are ok (isValid returns true), the postAuth-method of your plugin will be called and the profile will be saved.
4.2. If the username or password are not ok (isValid returns false), a ValidationException will be thrown

The validate-method of the Validationable interface can be explicitly called via REST by using following REST calls:
- POST /datasources/{username}/validate/{profileId}
- POST /datasinks/{username}/validate/{profileId}
- POST /jobs/{username}/validate/{jobId}
  These calls return specific error messages (collected by the Validator) about a certain profile or backup job.
  As far as i know, these REST calls are currently not being used by the front end.

**Comment by WolfgangEibner** [comment]
Validation should be automatically done at job creation/saving to save extra UI->Core calls.

**Comment by WolfgangEibner** [comment]
According to todays meeting validation is now done automatically.

**Comment by ghost** [comment]
Deployed and tested on dev01 & dev02
