### ISSUE TITLE
Moodle, Twitter, Facebook-Plugin: consider configured plugin options

### ISSUE THREAD

**Issue by WolfgangEibner** [backmeup/backmeup-prototype#67]
The mentioned plugins should consider the currently configured options. E.g. if photos should be downloaded.

**Comment by ghost** [comment]
The downloadAll method now receives a List<String> of selected options. If this list is not empty, the user selected certain data he wants to download.

**Comment by fjungwirth** [comment]
Twitter and Facebook plugins already consider options, Moodle will follow next week

**Comment by fjungwirth** [comment]
Seems like the options don't get passed to the plugins, because no matter what is selected, the backup is always the same

**Comment by WolfgangEibner** [comment]
I'm not sure, but I think Fabian said, that the core is passing the options to the plugins already. Bug in UI?

**Comment by ghost** [comment]
Currently we have the createBackUpJob-REST-Call which creates a new job and schedules it immediately.
This is however insufficient, as we have additional REST-Calls which update the selected options of the source and action plugins (e.g. I'd like to backup photos only and the encryption plugin shall use "xyz" as encryption key).

If you change the settings of the backup job, those settings won't be visible for the first time the job is executed. 

To resolve this problem we need two separate calls resulting in following workflow:
- The first call creates the job and stores it within the database. It doesn't schedule the job.
- After that, the user chooses the datasource options / action options, which update the job (the REST calls for this are already available).
- After configuring the job, a REST-call has to be made indicating that the job should be scheduled now.

I propose following changes:

```
# first call - creating the job object within the database
POST /jobs/{username} # creates a new job object within the database and returns the validation results of the used plugins. The parameters will be the same as described on Plone.

# second call - scheduling the job created before
POST /jobs/{username}/{jobId}/schedule # schedules a previously created job using the JobManager implementation. POST-Arguments: The password of the user to get a valid token from the keyserver.
```

**Comment by ghost** [comment]
The createBackUpJob-REST-Call is now capable of receiving in all source and action options (#87).
Therefore the plugins should be able to get the items which shall be backed up!

**Comment by WolfgangEibner** [comment]
@fjungwirth: Could you please check Moodle and/or Facebook plugin if they get the chosen options and if they download only the specified parts?

**Comment by WolfgangEibner** [comment]
Facebook seems to be ok (tested by me), Moodle too (tested by Florian).
Please test Twitter (I have no account) and close issue if all goes well.
