### ISSUE TITLE
wrong errorMessage for [GET] /users/{verificationKey}/verifyEmail

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#68]
requesting

```
/users/asdf/verifyEmail
```

which is obviously invalid (asdf is no existing verificationKey)

returns a error - so far so good. but the errorMessage has (still) "dynamic" content in it.

``` javascript
{
  errorMessage: "Failed to verify key asdf",
  ...
```

please change the message to something like "Failed to verify key" or "Failed to verify email".

**Comment by ghost** [comment]
Tested on dev01
