### ISSUE TITLE
user login not possible after registration

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#7]
IS:
can't login after registration
{"errorMessage":"User sepp6 has not been activated!","errorType":"org.backmeup.model.exceptions.UserNotActivatedException"}

SHOULD:
user should be able to login (no matter if email verification was done or not)

**Comment by ghost** [comment]
Fixed with Revision 311714cd5278e9e6a0bcd3c0fc219c848ddbd1bf

**Comment by keros** [comment]
Is now to late but maybe we should discuss this point. What should we do with an non verified E-Mail address? Why should we send this E-Mail if we not use it for user verification?

**Comment by ghost** [comment]
User verification takes place during all other REST calls, only login has been changed as proposed here. 

But yes, following solution might be more appropriate: 
The web ui should login even though a UserNotActivatedException occurs. In case of this exception, it should only show a button / link to request a new verification email (plus an additional way to change the entered email address).

the web ui might create a new verification email by using the REST call: `/users/{username}/newVerificationEmail`

**Comment by fetzig** [comment]
> The web ui should login even though a UserNotActivatedException occurs.

so how does the "web ui" know if the users password is correct...

**Comment by ghost** [comment]
The core could check the password before it checks the activation state, resulting in an InvalidCredentialsException instead of a UserNotActivatedException. If the password + username is ok, but the user has not been activated, a UserNotActivatedException would be raised.

As an alternative we could simply add another REST method, e.g.: `/users/{username}/activated` returning 201 NO_CONTENT (if active) or 400 UserNotActivatedException (if not active).

**Comment by fetzig** [comment]
> The core could check the password before it checks the activation state, resulting in an InvalidCredentialsException instead of a UserNotActivatedException. If the password + username is ok, but the user has not been activated, a UserNotActivatedException would be raised.

-1

way to obscure, even if the docu would cover all possible exceptions (which it doesn't).

> As an alternative we could simply add another REST method, e.g.: `/users/{username}/activated` returning 201 NO_CONTENT (if active) or 400 UserNotActivatedException (if not active).

imo the UserNotActivatedException shouldn't be triggered by the "/users/{username}/login" call. you can respond json data describing the state of the user when a login[sic] request is made. i.e.:

``` javascript
{
  "activated": false
}
```

UserNotActivatedException can be returned after petty much all the other rest calls.
