### ISSUE TITLE
rest api: get rid of 204/no content response

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#75]
frontend ALWAYS needs response message. please add success messages to following requests:
- [DELETE] /users/{username}
- [PUT] /users/{username}
- [POST] /users/{username}/login
- [POST] /users/{username}/properties/{property}/{value}
- [DELETE] /users/{username}/properties/{property}
- [DELETE] /datasources/{username}/profiles/{datasourceProfileId}
- [PUT] /datasources/{username}/profiles/{profileId}/{jobId}
- [POST] /datasources/{username}/{profileId}/auth/post
- [DELETE] /datasinks/{username}/profiles/{datasinkProfileId}
- [POST] /datasinks/{username}/{profileId}/auth/post
- [DELETE] /jobs/{username}/{jobId}

suggestion:

``` javascript
{
    'type': 'success', // info|success|warning|error
    'message': "Account password has been changed."
}
```

putting (possibly) multiple messages into an array could be handy in some cases:

``` javascript
{
    'type': 'success', // info|success|warning|error
    'messages': [
      "Account password has been changed.",
      "Account email has been changed, please check your mailbox for 'activation email'."
    ]
}

```

**Comment by ghost** [comment]
deployed and tested on dev01
