### ISSUE TITLE
rest api: [GET] /jobs/{username} missing properties

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#76]
the two properties "lastBackup" and "nextBackup" in the response of /jobs/{username} are needed for every single backup job. 

"global" nextBackup and lastBackup timestamps, as currently implemented, don't hurt but are currently not necessary (and where never requested...).

thx.

**Comment by ghost** [comment]
deployed and tested on dev01

**Comment by fetzig** [comment]
nextBackup is in the past...
