### ISSUE TITLE
verifyEmail call insufficient

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#8]
IS:
calling "/users/{verificationKey}/verifyEmail" responds with 204 if the hash is correct.

SHOULD:
"/users/{verificationKey}/verifyEmail" should respond the users username. so backmeup-frontend knows which user has been verified.

``` javascript
{
  "username": "sepp"
}
```

**Comment by ghost** [comment]
Changed response code to 200 and added username to result data.
