### ISSUE TITLE
encryption plugin not working

### ISSUE THREAD

**Issue by keros** [backmeup/backmeup-prototype#81]
The Encryption plugin does not work because the password is not delivered to it.
The "org.backmeup.encryption.password" property is missing.

**Comment by WolfgangEibner** [comment]
Either we need an option for this action plugin or we simple use the user password (which is somehow not very flexible).

@fschoeppl : Should we discuss this at the next meeting, what is your opinion?

**Comment by ghost** [comment]
To pass in a org.backmeup.encryption.password we need to store it somewhere (e.g. keyserver). We are going to need two "new" features:
- The action plugins need to return a List<String> which have to be entered by the user
- These inputs must then be stored within the keyserver. Therefore we need to extend the core & keyserver.client to be able to store action specific data.
- Finally, when running the job, the keyserver has to return the password to the JobRunner which passes the data to the action plugin.

**Comment by WolfgangEibner** [comment]
Should be similar to #64.

**Comment by ghost** [comment]
We might now store the password within the core database by specifying it during the backup creation.
I'll take a look if I can handle the encryption password differently (storing it within the keyserver)

**Comment by ghost** [comment]
To manage the encryption property within the keyserver, I'd need following methods:
- POST /actions/{username}/{jobId}/{propertyKey}/{propertyValue}
  Stores / overrides a property of a user's job and encrypts it with {keyRing}
  Additional POST-Parameters
  {keyRing}, which will be used to encrypt / decrypt the properties
- DELETE /actions/{username}/{jobId}/{propertyKey}/{propertyValue}
  which deletes a property
  Note: If user gets deleted, also delete all of her/his properties!
- A way to retrieve those properties, maybe by using the token service:
  e.g. by 
  POST /tokens/tokens
  {
  "bmu_user_id" : ...,
  // values as before
  ...
  "reusable" : ...,
  // new request for a job's data
  "job_id" : 1234
  }

Gives a token which will in exchange return the job 1234's encrypted properties:

POST /tokens/data
{
  token : "myToken1231j3wjklsfjs",
  bmu_token_id  : 45543
}
Returning:
{
  // data as before  
  ...,
  // plus the jobs specific data
  job {
    "org.backmeup.encryption" : "password",
  }
}

Feel free to comment and improve my suggestion!

**Comment by WolfgangEibner** [comment]
Implemented, but not with the best solution. Maybe we should open a new issue regarding the enhancement and close this one as the initial problem is already solved.
