### ISSUE TITLE
make search types a little less detailed....

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#82]
- splitting search result items into types is great.
- types beeing mimetypes is IMHO a little much...
- types beeing mimetypes + charset (like http's conenty-type) is definitely to much:

``` javascript
byType: [
  {
    count: 1,
    title: "text/html; charset=UTF-8"
  },
  {
    count: 1,
    title: "text/plain; charset=ISO-8859-1"
  }
]
```

**Comment by rsimon** [comment]
I reduced the 'resolution' to MIME-type only. The question is whether reducing further in the core wouldn't loose a bit too much information: it might be useful later on and/or for other frontend developers. 

Also, it's quite easy to filter just the part before the '/' in the frontend, and then eg. group by: 
- text
- image
- video
- audio
- message
- everything else

**Comment by fetzig** [comment]
mime types are not very useful at the frontend and there is definitely more to do than stripping the second part. i.e.:
application/pdf, application/ogg.

frontend has no clue about what files/mime-types are indexed by the search. so definitely not a frontend task.

**Comment by rsimon** [comment]
I don't know what exactly you expect the grouping to be like, other than "image", "text", "video", "audio", "anything else" - can you suggest the categorization vocabulary you would like to have in the UI?

**Comment by fetzig** [comment]
mimetypes aren't useful.

looking at the concept: "image", "text", "video", "audio" and "other" maybe

**Comment by rsimon** [comment]
Now implemented like that & active on dev01 and dev02.

**Comment by fetzig** [comment]
still mimetypes...

**Comment by rsimon** [comment]
Example: (just tested now)

http://bmu-dev02.x:8080/backups/TestUser/11/query

```
{
   "progress":0,
   "files":[
      {
         "type":"image/jpeg",
         "timeStamp":1352798707664,
         "title":"images.jpg",
         "fileId":"20:49bce6098ca9ecc77b2ba301c342353d:1352798707664"
      },
      {
         "type":"image/jpeg",
         "timeStamp":1352798707169,
         "title":"images.jpg",
         "fileId":"20:49bce6098ca9ecc77b2ba301c342353d:1352798707169"
      },
      {
         "type":"image/jpeg",
         "timeStamp":1352798704304,
         "title":"images.jpg",
         "fileId":"20:49bce6098ca9ecc77b2ba301c342353d:1352798704304"
      },
      {
         "type":"application/pdf",
         "timeStamp":1352798706083,
         "title":"ICS-Kalender-Import.pdf",
         "fileId":"20:bb664a1fc414289ea202c87a78d73255:1352798706083"
      },
      {
         "type":"application/pdf",
         "timeStamp":1352798707426,
         "title":"ICS-Kalender-Import.pdf",
         "fileId":"20:bb664a1fc414289ea202c87a78d73255:1352798707426"
      },
      {
         "type":"application/pdf",
         "timeStamp":1352798707876,
         "title":"ICS-Kalender-Import.pdf",
         "fileId":"20:bb664a1fc414289ea202c87a78d73255:1352798707876"
      }
   ],
   "bySource":[
      {
         "count":6,
         "title":"org.backmeup.mail"
      }
   ],
   "byType":[
      {
         "count":3,
         "title":"text"
      },
      {
         "count":3,
         "title":"image"
      }
   ],
   "searchQuery":"backmeup"
}
```

Mind the "byType" - two groups, one "image", one "text", 3 results each.

**Comment by rsimon** [comment]
Ok, I see - you want the same types in the files list as well. Fix coming up...

**Comment by rsimon** [comment]
Now active on dev01 & dev02
