### ISSUE TITLE
should we "auto-login" after user has verified email

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#93]
hi,

IS:
- user isn't logged in after registration
- user isn't logged in after verifying email

backmeup-frontend could log the user in after registration and/or email verification. i'm going to implement this.

is there any security concern/feedback/... ?

**Comment by WolfgangEibner** [comment]
I don't think so...

**Comment by fetzig** [comment]
just realized that i can't login after verifying the email, but right after registration. so i'll do only that.
