### ISSUE TITLE
rest api: missing property [GET] /data[sources|sinks]/{username}/profiles

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#97]
property 'identification' is missing in profiles created since yesterday.

**Comment by WolfgangEibner** [comment]
Maybe some wrong commit/merge?
@fschoeppl: Could you please check that?

**Comment by WolfgangEibner** [comment]
seems to be caused by #98

**Comment by fetzig** [comment]
fine again.
